import type { Metadata } from "next";
import { MarketingHeader } from "@/components/marketing/marketing-header";
import { MarketingFooter } from "@/components/marketing/marketing-footer";

export const metadata: Metadata = {
  title: "Terms of Service — AptDesigner",
  description: "The terms under which you use AptDesigner.",
};

export default function TermsPage() {
  const updatedDate = "April 16, 2026";

  return (
    <div className="min-h-screen bg-background flex flex-col">
      <MarketingHeader />

      <main className="flex-1 max-w-3xl mx-auto px-6 md:px-8 py-16">
        <div className="mb-10">
          <h1 className="text-4xl font-bold tracking-tight mb-3">Terms of Service</h1>
          <p className="text-sm text-muted-foreground">Last updated: {updatedDate}</p>
        </div>

        <div className="prose prose-stone dark:prose-invert max-w-none space-y-8 text-[15px] leading-relaxed">
          <section>
            <h2 className="text-xl font-semibold mb-3">1. Agreement</h2>
            <p className="text-muted-foreground">
              By creating an account and using AptDesigner (&quot;the Service&quot;),
              you agree to these Terms. If you don&apos;t agree, please don&apos;t
              use the Service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">2. Your content</h2>
            <p className="text-muted-foreground">
              You retain full ownership of everything you upload — photos,
              floor plans, notes, and generated designs. We never sell or share
              your content with third parties beyond the AI models required to
              produce your designs. You grant us a limited license to process
              your content solely to operate the Service for you.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">3. AI-generated recommendations</h2>
            <p className="text-muted-foreground">
              Product recommendations, design directions, and mockups are
              generated by AI and provided as suggestions. We do our best to
              ensure quality, but we don&apos;t guarantee that any specific piece
              will fit perfectly, be in stock, or match your taste exactly.
              Verify measurements, availability, and suitability before purchasing.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">4. Third-party retailers</h2>
            <p className="text-muted-foreground">
              AptDesigner links to products on third-party retailers. We don&apos;t
              sell furniture directly. Your purchase, return, shipping, and
              warranty terms are between you and the retailer.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">5. Acceptable use</h2>
            <p className="text-muted-foreground">
              Don&apos;t upload content you don&apos;t have rights to, don&apos;t
              try to reverse-engineer the Service, and don&apos;t use AptDesigner
              to harass, harm, or defraud anyone. We may suspend accounts that
              violate these rules.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">6. Payments & refunds</h2>
            <p className="text-muted-foreground">
              Paid tiers are billed as described on the pricing page. We offer
              a 30-day money-back guarantee — email us within 30 days of
              purchase and we&apos;ll refund you in full.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">7. Disclaimers</h2>
            <p className="text-muted-foreground">
              The Service is provided &quot;as is.&quot; We don&apos;t warrant
              that the Service will be uninterrupted or error-free. To the fullest
              extent permitted by law, we aren&apos;t liable for indirect or
              consequential damages arising from your use of the Service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">8. Changes</h2>
            <p className="text-muted-foreground">
              We may update these Terms from time to time. Material changes
              will be communicated by email or on this page. Continued use after
              changes means you accept the updated Terms.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">9. Contact</h2>
            <p className="text-muted-foreground">
              Questions? Reach us at{" "}
              <a href="mailto:hello@aptdesignerai.com" className="text-accent-warm font-medium hover:underline">
                hello@aptdesignerai.com
              </a>
              .
            </p>
          </section>
        </div>
      </main>

      <MarketingFooter />
    </div>
  );
}
