// Waitlist welcome email — fires once, right after double opt-in confirmation
// (E7.1 -> E7.2). This is "Email 1" of the welcome sequence in
// docs/email-welcome-sequence.md; it confirms the subscriber is on the list and
// sets expectations for launch. Copy is grounded only in what the product
// actually does (no invented metrics, no emoji, calm-warm tone — matches the
// sequence doc). Keep in sync with docs/email-welcome-sequence.md Email 1.
//
// CAN-SPAM: lib/email/index.ts classifies stage "waitlist_welcome_1" as
// marketing (not in TRANSACTIONAL_STAGES), and its dry-run gate only checks
// that EMAIL_PHYSICAL_ADDRESS is SET on the deployment — it does not inspect
// the rendered email. So the footer here must actually render a WORKING
// unsubscribe link + physical address once that env var is set, or a "gate
// passed" send would still go out non-compliant.
//
// The unsubscribe link deliberately does NOT point at /account (unlike
// lib/email/templates/lifecycle.ts's marketing-stage footer): lifecycle.ts's
// recipients are signed-in app users, but a waitlist_emails subscriber never
// gets a Supabase auth account (app/api/waitlist/route.ts and
// app/api/waitlist/confirm/route.ts never call supabase.auth), so /account
// would just bounce them to a login wall they have no credentials for. CAN-
// SPAM requires an opt-out that works WITHOUT a login, so this links to the
// public app/api/waitlist/unsubscribe endpoint instead, authenticated by the
// waitlist row's own unguessable `id` — the same unguessable-token-as-auth
// pattern already used for confirmation_token on this same table.

function physicalAddress(): string | null {
  const addr = process.env.EMAIL_PHYSICAL_ADDRESS?.trim();
  return addr && addr.length > 0 ? addr : null;
}

export interface WaitlistWelcomeEmail {
  subject: string;
  html: string;
  text: string;
}

/**
 * Build the welcome email sent once a waitlist sign-up is confirmed.
 * `siteUrl` + `waitlistId` (the confirmed waitlist_emails row's own `id`) are
 * used only to build the unsubscribe link — there is no other user-influenced
 * input, so nothing else needs escaping. `waitlistId` is a UUID generated by
 * Postgres, never client-supplied, so it is safe to interpolate directly.
 */
export function buildWaitlistWelcomeEmail(siteUrl: string, waitlistId: string): WaitlistWelcomeEmail {
  const unsubscribeUrl = `${siteUrl}/api/waitlist/unsubscribe?id=${waitlistId}`;
  const subject = "You're on the list — here's what's coming";

  const html = `<!DOCTYPE html>
<html lang="en">
  <body style="margin:0;padding:0;background:#faf8f5;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;color:#2b2722;">
    <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:#faf8f5;padding:32px 16px;">
      <tr>
        <td align="center">
          <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="max-width:520px;background:#ffffff;border:1px solid #ece5db;border-radius:16px;overflow:hidden;">
            <tr>
              <td style="padding:36px 36px 8px 36px;">
                <p style="margin:0 0 4px 0;font-size:13px;letter-spacing:0.08em;text-transform:uppercase;color:#b07a4f;font-weight:600;">AptDesignerAI</p>
                <h1 style="margin:0 0 16px 0;font-size:24px;line-height:1.25;font-weight:700;color:#2b2722;">You're on the early-access list</h1>
                <p style="margin:0 0 16px 0;font-size:16px;line-height:1.6;color:#4a443c;">
                  Thanks for confirming. You're set for early access to AptDesignerAI —
                  an AI that reads your apartment photos and tells you exactly what to
                  do with them. Here's what to expect at launch:
                </p>
                <p style="margin:0 0 12px 0;font-size:16px;line-height:1.6;color:#4a443c;">
                  <strong style="color:#2b2722;">On your phone.</strong> Point your camera
                  at any room. In about 30 seconds you'll have a design direction
                  (palette, materials, style notes), a read on what's working and what
                  isn't, and product recommendations scored against your actual space.
                </p>
                <p style="margin:0 0 12px 0;font-size:16px;line-height:1.6;color:#4a443c;">
                  <strong style="color:#2b2722;">Honest recommendations.</strong> Every
                  furniture pick is scored for scale against your room dimensions,
                  palette compatibility, and style coherence — you see the reasoning,
                  not just a product card.
                </p>
                <p style="margin:0 0 24px 0;font-size:16px;line-height:1.6;color:#4a443c;">
                  <strong style="color:#2b2722;">The whole apartment.</strong> Design
                  rooms in any order. The AI keeps a shared style thread, so your
                  bedroom doesn't end up looking like a different apartment from your
                  living room.
                </p>
                <p style="margin:0 0 8px 0;font-size:16px;line-height:1.6;color:#4a443c;">
                  We'll email you the moment the app is live on the App Store and
                  Google Play.
                </p>
              </td>
            </tr>
            <tr>
              <td style="padding:8px 36px 32px 36px;border-top:1px solid #ece5db;">
                <p style="margin:16px 0 8px 0;font-size:12px;line-height:1.6;color:#a39a8f;">
                  You're receiving this because you confirmed your spot on the
                  AptDesignerAI waitlist. We'll only email you about the launch.
                  <a href="${unsubscribeUrl}" style="color:#a39a8f;">Unsubscribe</a>
                </p>
                ${physicalAddress() ? `<p style="margin:0;font-size:12px;line-height:1.6;color:#a39a8f;">${physicalAddress()}</p>` : ""}
              </td>
            </tr>
          </table>
        </td>
      </tr>
    </table>
  </body>
</html>`;

  const text = [
    "You're on the list — here's what's coming",
    "",
    "Thanks for confirming. You're set for early access to AptDesignerAI — an AI",
    "that reads your apartment photos and tells you exactly what to do with them.",
    "",
    "What to expect at launch:",
    "- On your phone: point your camera at any room. In ~30 seconds you'll have a",
    "  design direction (palette, materials, style notes), a read on what's working",
    "  and what isn't, and product recommendations scored against your actual space.",
    "- Honest recommendations: every pick is scored for scale, palette compatibility,",
    "  and style coherence — you see the reasoning, not just a product card.",
    "- The whole apartment: design rooms in any order; the AI keeps a shared style",
    "  thread across them.",
    "",
    "We'll email you the moment the app is live on the App Store and Google Play.",
    "",
    `To unsubscribe: ${unsubscribeUrl}`,
    ...(physicalAddress() ? [physicalAddress() as string] : []),
  ].join("\n");

  return { subject, html, text };
}
